"""Studio request authentication (FR-040/FR-040a, research.md R6).

Loopback binding alone is not trusted: a hostile page in the same browser
(CSRF/DNS-rebinding) or another local user reaches 127.0.0.1 too. Every
request passes, in order: loopback peer → Host allowlist → Origin /
Sec-Fetch-Site on mutations → per-launch token. The token is generated by
`rmu studio`, lives only in process memory, and is exchanged for an HttpOnly
SameSite=Strict cookie on first load so it does not linger in the address bar.
Mutations additionally require the token in an `X-Studio-Token` header (HTMX
sends it globally), so a cookie alone can never drive a state change.

Failures are a uniform 403 with a restart hint — never which check failed.
"""

from __future__ import annotations

import hmac
import ipaddress
from dataclasses import dataclass
from urllib.parse import parse_qs

COOKIE_NAME = "studio_session"
HEADER_NAME = "x-studio-token"
MUTATING_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})

_REFUSAL_BODY = (
    b"<!doctype html><html><body><h1>403 &mdash; studio access refused</h1>"
    b"<p>This request failed the studio's locality checks. If your studio URL "
    b"is stale, restart the server with <code>rmu studio</code> and use the "
    b"freshly printed URL.</p></body></html>"
)


@dataclass(frozen=True)
class LaunchContext:
    """Per-launch security context (data-model.md StudioLaunch). Memory-only."""

    token: str
    port: int

    def allowed_hosts(self) -> frozenset[str]:
        return frozenset({
            f"127.0.0.1:{self.port}", f"localhost:{self.port}",
            "127.0.0.1", "localhost",
        })

    def allowed_origins(self) -> frozenset[str]:
        return frozenset({
            f"http://127.0.0.1:{self.port}", f"http://localhost:{self.port}",
        })


def _is_loopback(host: str | None) -> bool:
    if not host:
        return False
    if host == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def _headers(scope) -> dict[str, str]:
    return {k.decode("latin-1").lower(): v.decode("latin-1")
            for k, v in scope.get("headers", [])}


def _cookie(headers: dict[str, str]) -> str | None:
    raw = headers.get("cookie", "")
    for part in raw.split(";"):
        name, _, value = part.strip().partition("=")
        if name == COOKIE_NAME:
            return value
    return None


def _token_ok(candidate: str | None, token: str) -> bool:
    return candidate is not None and hmac.compare_digest(candidate, token)


def request_allowed(scope, ctx: LaunchContext) -> bool:
    """The full check ladder for one HTTP request scope."""
    client = scope.get("client")
    if client is None or not _is_loopback(client[0]):
        return False

    headers = _headers(scope)
    if headers.get("host") not in ctx.allowed_hosts():
        return False

    method = scope.get("method", "GET").upper()
    if method in MUTATING_METHODS:
        origin = headers.get("origin")
        if origin is not None and origin not in ctx.allowed_origins():
            return False
        fetch_site = headers.get("sec-fetch-site")
        if fetch_site is not None and fetch_site not in ("same-origin", "none"):
            return False
        if not _token_ok(headers.get(HEADER_NAME), ctx.token):
            return False

    # Token: the URL-key exchange on "/" is the single cookieless entry point.
    if scope.get("path") == "/" and method == "GET":
        key = parse_qs(scope.get("query_string", b"").decode("latin-1")).get("key")
        if key and _token_ok(key[0], ctx.token):
            return True
    return _token_ok(_cookie(headers), ctx.token)


class StudioAuthMiddleware:
    """Pure ASGI middleware so static files and errors are covered too."""

    def __init__(self, app, ctx: LaunchContext):
        self.app = app
        self.ctx = ctx

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        if not request_allowed(scope, self.ctx):
            await send({
                "type": "http.response.start",
                "status": 403,
                "headers": [(b"content-type", b"text/html; charset=utf-8"),
                            (b"cache-control", b"no-store")],
            })
            await send({"type": "http.response.body", "body": _REFUSAL_BODY})
            return
        await self.app(scope, receive, send)
